"""Add referentially consistent synthetic data for development and demos.

The script never clears the database by default. Pass ``--replace`` to remove
only records owned by accounts generated by this script (usernames beginning
with ``generated_``).
"""

from __future__ import annotations

import argparse
import random
import sys
from datetime import datetime, timedelta
from pathlib import Path

from faker import Faker

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common.database import connect  # noqa: E402


DEMO_PASSWORD_HASH = "$2y$10$w0U5TpppKkS3cQtw5lvNS.J/hs7H4M6LA7MQPDXlgkteJu6ldnACy"
ORDER_STATUSES = [
    "pending",
    "preparing",
    "ready_for_pickup",
    "delivering",
    "completed",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--customers", type=int, default=20)
    parser.add_argument("--couriers", type=int, default=5)
    parser.add_argument("--owners", type=int, default=2)
    parser.add_argument("--orders", type=int, default=60)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--replace",
        action="store_true",
        help="remove only data previously generated by this script",
    )
    return parser.parse_args()


def create_user(cursor, username: str, role: str, email: str) -> int:
    cursor.execute(
        "INSERT INTO users (username, password, user_type) VALUES (%s, %s, %s)",
        (username, DEMO_PASSWORD_HASH, role),
    )
    user_id = int(cursor.lastrowid)
    cursor.execute("INSERT INTO email (user_id, email) VALUES (%s, %s)", (user_id, email))
    return user_id


def remove_generated_data(cursor) -> None:
    """Delete only rows belonging to previously generated demo accounts."""
    cursor.execute("SELECT user_id FROM users WHERE username LIKE 'generated\\_%'")
    generated_users = [int(row["user_id"]) for row in cursor.fetchall()]
    if generated_users:
        placeholders = ",".join(["%s"] * len(generated_users))
        cursor.execute(
            f"DELETE FROM `order` WHERE user_id IN ({placeholders})",
            tuple(generated_users),
        )
        cursor.execute(
            f"DELETE FROM cart WHERE user_id IN ({placeholders})",
            tuple(generated_users),
        )

    if generated_users:
        cursor.execute(
            f"""DELETE FROM restaurant
                WHERE restaurant_id IN (
                    SELECT restaurant_id FROM owns
                    WHERE user_id IN ({placeholders})
                )""",
            tuple(generated_users),
        )
        cursor.execute(
            f"DELETE FROM users WHERE user_id IN ({placeholders})",
            tuple(generated_users),
        )


def main() -> None:
    args = parse_args()
    rng = random.Random(args.seed)
    Faker.seed(args.seed)
    faker = Faker("zh_TW")

    connection = connect()
    cursor = connection.cursor(dictionary=True)

    try:
        if args.replace:
            remove_generated_data(cursor)

        customers = []
        for index in range(args.customers):
            user_id = create_user(
                cursor,
                f"generated_customer_{args.seed}_{index + 1}",
                "Customer",
                f"generated.customer.{args.seed}.{index + 1}@example.com",
            )
            cursor.execute(
                """
                INSERT INTO customer
                    (user_id, daily_calorie_goal, customer_address, phone)
                VALUES (%s, %s, %s, %s)
                """,
                (user_id, rng.randrange(1600, 2601, 100), faker.address(), faker.phone_number()[:20]),
            )
            cursor.execute(
                "INSERT INTO cmnpaymethod (user_id, cmnPayMethod) VALUES (%s, %s)",
                (user_id, rng.choice(["Credit Card", "LINE Pay", "Cash"])),
            )
            customers.append(user_id)

        couriers = []
        for index in range(args.couriers):
            user_id = create_user(
                cursor,
                f"generated_delivery_{args.seed}_{index + 1}",
                "DeliveryPerson",
                f"generated.delivery.{args.seed}.{index + 1}@example.com",
            )
            cursor.execute(
                """
                INSERT INTO deliveryperson (user_id, rating, vehicle_type)
                VALUES (%s, %s, %s)
                """,
                (user_id, round(rng.uniform(3.5, 5.0), 2), rng.choice(["Bicycle", "Motorcycle"])),
            )
            couriers.append(user_id)

        categories = []
        cursor.execute("SELECT category_id FROM category")
        categories = [int(row["category_id"]) for row in cursor.fetchall()]
        if not categories:
            for name in ["主食", "點心", "飲品"]:
                cursor.execute("INSERT INTO category (category) VALUES (%s)", (name,))
                categories.append(int(cursor.lastrowid))

        for owner_index in range(args.owners):
            owner_id = create_user(
                cursor,
                f"generated_owner_{args.seed}_{owner_index + 1}",
                "RestaurantOwner",
                f"generated.owner.{args.seed}.{owner_index + 1}@example.com",
            )
            cursor.execute("INSERT INTO restaurantowner (user_id) VALUES (%s)", (owner_id,))
            cursor.execute(
                """
                INSERT INTO restaurant
                    (restaurantAddress, restaurantName, operationTime, latitude, longitude)
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    faker.address(),
                    f"測試餐廳 {args.seed}-{owner_index + 1}",
                    "11:00-20:00",
                    round(22.63 + rng.random() * 0.06, 6),
                    round(120.26 + rng.random() * 0.08, 6),
                ),
            )
            restaurant_id = int(cursor.lastrowid)
            cursor.execute(
                "INSERT INTO owns (restaurant_id, user_id) VALUES (%s, %s)",
                (restaurant_id, owner_id),
            )

            for item_index in range(4):
                cursor.execute(
                    """
                    INSERT INTO menuitem
                        (restaurant_id, price, foodName, calories, main_dish)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    (
                        restaurant_id,
                        rng.randrange(70, 251, 5),
                        f"測試餐點 {args.seed}-{owner_index + 1}-{item_index + 1}",
                        rng.randrange(250, 901, 10),
                        "測試主餐",
                    ),
                )
                item_id = int(cursor.lastrowid)
                cursor.execute("INSERT INTO has VALUES (%s, %s)", (restaurant_id, item_id))
                cursor.execute(
                    "INSERT INTO menuitem_category VALUES (%s, %s)",
                    (item_id, rng.choice(categories)),
                )

        cursor.execute("SELECT item_id, price, calories, restaurant_id FROM menuitem")
        menu_items = cursor.fetchall()
        items_by_restaurant = {}
        for item in menu_items:
            items_by_restaurant.setdefault(int(item["restaurant_id"]), []).append(item)
        if not menu_items:
            raise RuntimeError("No menu items are available for order generation.")

        now = datetime.now().replace(microsecond=0)
        for order_index in range(args.orders):
            customer_id = rng.choice(customers)
            username = f"generated_customer_{args.seed}_{customers.index(customer_id) + 1}"
            restaurant_id = rng.choice(list(items_by_restaurant))
            restaurant_items = items_by_restaurant[restaurant_id]
            selected = rng.sample(
                restaurant_items,
                k=min(rng.randint(1, 3), len(restaurant_items)),
            )
            quantities = [rng.randint(1, 3) for _ in selected]
            total_price = sum(float(item["price"]) * qty for item, qty in zip(selected, quantities))
            total_calories = sum(int(item["calories"] or 0) * qty for item, qty in zip(selected, quantities))
            status = rng.choice(ORDER_STATUSES)

            cursor.execute("INSERT INTO cart (user_id) VALUES (%s)", (customer_id,))
            cart_id = int(cursor.lastrowid)
            cursor.execute(
                """
                INSERT INTO `order`
                    (weather, order_status, order_time, total_price, orderCustomer,
                     orderPayMethod, total_calories, user_id, cart_id, order_ps,
                     delivery_lat, delivery_lng)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    rng.choice(["晴", "多雲", "雨"]),
                    status,
                    now - timedelta(hours=rng.randint(1, 720)),
                    total_price,
                    username,
                    rng.choice(["Credit Card", "LINE Pay", "Cash"]),
                    total_calories,
                    customer_id,
                    cart_id,
                    None,
                    round(22.63 + rng.random() * 0.06, 6),
                    round(120.26 + rng.random() * 0.08, 6),
                ),
            )
            order_id = int(cursor.lastrowid)

            for sq_no, (item, quantity) in enumerate(zip(selected, quantities), start=1):
                cursor.execute(
                    "INSERT INTO orderitem VALUES (%s, %s, %s)",
                    (order_id, sq_no, quantity),
                )
                cursor.execute(
                    "INSERT INTO contains VALUES (%s, %s, %s)",
                    (order_id, sq_no, item["item_id"]),
                )

            if status in {"ready_for_pickup", "delivering", "completed"}:
                courier_id = rng.choice(couriers)
                first_item = selected[0]
                cursor.execute(
                    "SELECT latitude, longitude FROM restaurant WHERE restaurant_id = %s",
                    (first_item["restaurant_id"],),
                )
                pickup = cursor.fetchone()
                cursor.execute(
                    """
                    INSERT INTO delivers
                        (order_id, user_id, deliver_status, deliver_time,
                         current_lat, current_lng, pickup_lat, pickup_lng,
                         dropoff_lat, dropoff_lng)
                    SELECT %s, %s, %s, %s, %s, %s, %s, %s,
                           delivery_lat, delivery_lng
                    FROM `order` WHERE order_id = %s
                    """,
                    (
                        order_id,
                        courier_id,
                        status,
                        now if status == "completed" else None,
                        round(22.63 + rng.random() * 0.06, 6),
                        round(120.26 + rng.random() * 0.08, 6),
                        pickup["latitude"],
                        pickup["longitude"],
                        order_id,
                    ),
                )

            if status == "completed":
                cursor.execute(
                    """
                    INSERT INTO review (user_id, order_id, rating, comment)
                    VALUES (%s, %s, %s, %s)
                    """,
                    (customer_id, order_id, rng.randint(1, 5), faker.sentence()),
                )

        connection.commit()
        print(
            f"Generated {args.customers} customers, {args.couriers} couriers, "
            f"{args.owners} owners and {args.orders} orders."
        )
    except Exception:
        connection.rollback()
        raise
    finally:
        cursor.close()
        connection.close()


if __name__ == "__main__":
    main()
